name: Formatting Review

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ./vcpkg
          key: ${{ runner.os }}-${{ hashFiles('scripts/bootstrap*') }}

      - name: bootstrap
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./bootstrap-vcpkg.sh

      - name: Formatting
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "none@none.none"
          git config user.name "none"

          ./vcpkg format-manifest ports/*/vcpkg.json
          git add -u
          git commit -m "tmp"
          ./vcpkg x-add-version --overwrite-version --all --skip-formatting-check
          git reset HEAD~ --mixed

          TMPFILE=$(mktemp)
          git diff >"${TMPFILE}"
          reviewdog -f=diff -f.diff.strip=1 -filter-mode=nofilter -reporter=github-pr-review < "${TMPFILE}"

      - name: View context attributes
        uses: actions/github-script@v4
        if: always()
        with:
          script: console.log(context)

      - uses: actions/github-script@v4
        if: always()
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })

      - uses: actions/github-script@v4
        if: always()
        with:
          script: |
            github.pulls.createReview({
              owner: context.repo.owner,
              pull_number: context.issue.number,
              repo: context.repo.repo,
              body: 'Did you remember to run `vcpkg x-add-version --all --overwrite-versions`?',
              event: 'REQUEST_CHANGES'
            })
