name: Formatting Review

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: PR head repo
        id: head_repo_name
        run: |
          HEAD_REPO_NAME=$(jq -r '.pull_request.head.repo.full_name' "$GITHUB_EVENT_PATH")
          echo "PR head repo: $HEAD_REPO_NAME"
          echo "::set-output name=repo::$HEAD_REPO_NAME"

      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.head_repo_name.outputs.repo }}
          fetch-depth: 0

      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ./vcpkg
          key: ${{ runner.os }}-${{ hashFiles('scripts/bootstrap*') }}

      - name: bootstrap
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./bootstrap-vcpkg.sh

      - name: Formatting
        run: |
          git config user.email "none@none.none"
          git config user.name "none"

          ./vcpkg format-manifest ports/*/vcpkg.json
          git diff >.github-pr.format-manifest
          git add -u
          git commit -m "tmp" --allow-empty
          ./vcpkg x-add-version --overwrite-version --all --skip-formatting-check
          git diff >.github-pr.x-add-version
          git reset HEAD~ --mixed

      - uses: actions/github-script@v4
        with:
          script: |
            const { promises: fs } = require('fs')
            const add_version = (await fs.readFile('.github-pr.x-add-version', 'utf8')).trim()
            const format = (await fs.readFile('.github-pr.format-manifest', 'utf8')).trim()

            var output = ''
            if (format !== "") {
              output += "Did you remember to format all modified manifest files?\n"
              output += "`./vcpkg format-manifest ports/*/vcpkg.json`\n"
              output += "```diff\n" + format + "\n```\n\n"
            }
            if (add_version !== "") {
              output += "Did you remember to update the version database after committing all other changes?\n"
              output += "`./vcpkg x-add-version --all --overwrite-versions`\n"
              output += "```diff\n" + add_version + "\n```\n\n"
            }

            if (output === "") {
              github.pulls.createReview({
                owner: context.repo.owner,
                pull_number: context.issue.number,
                repo: context.repo.repo,
                event: 'APPROVE'
              })
            }
            else {
              github.pulls.createReview({
                owner: context.repo.owner,
                pull_number: context.issue.number,
                repo: context.repo.repo,
                body: output,
                event: 'REQUEST_CHANGES'
              })
            }
