# Modelled after https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

# These "checks" are also performed as part of our critical-path azure-pipelines review,
# however here they are better able to post back to the original PR
name: PR Suggestions

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ./vcpkg
          key: ${{ runner.os }}-${{ hashFiles('scripts/bootstrap*') }}

      - name: bootstrap
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./bootstrap-vcpkg.sh

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR

      - name: Formatting
        run: |
          git config user.email github-actions
          git config user.name github-actions@github.com

          ./vcpkg format-manifest ports/*/vcpkg.json
          git diff > .github-pr.format-manifest
          git add -u
          git commit -m "tmp" --allow-empty
          git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin ${{ github.event.pull_request.base.sha }}
          git checkout ${{ github.event.pull_request.base.sha }} -- versions
          git restore --staged versions
          ./vcpkg x-add-version --all --skip-formatting-check
          git diff > .github-pr.x-add-version
          git reset HEAD~ --mixed

      - uses: actions/github-script@v4
        with:
          script: |
            const { promises: fs } = require('fs')
            const add_version = (await fs.readFile('.github-pr.x-add-version', 'utf8')).trim()
            const format = (await fs.readFile('.github-pr.format-manifest', 'utf8')).trim()

            var output = ''
            if (format !== "") {
              output += "All modified manifest files must be formatted:\n"
              output += "`./vcpkg format-manifest ports/*/vcpkg.json`\n"
              output += "```diff\n" + format + "\n```\n\n"
            }
            if (add_version !== "") {
              output += "After formatting, the version database must be updated:\n"
              output += "`git checkout ${{ github.event.pull_request.base.sha }} -- versions`\n"
              output += "`./vcpkg x-add-version --all --overwrite-versions`\n"
              output += "```diff\n" + add_version + "\n```\n\n"
            }

            if (output !== "") {
              await fs.writeFile("pr/event", "APPROVE")
            } else {
              await fs.writeFile("pr/event", "REQUEST_CHANGES")
            }
            await fs.writeFile("pr/body", output)

            console.log(output);

      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
